version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: koheda-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: koheda
      POSTGRES_USER: koheda
      POSTGRES_PASSWORD: koheda123
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
